site_name: LuaRT Academy

theme:
  name: material
  font: Yaldevi
  palette:
    primary: blue
    accent: amber
  icon:
    logo: material/school
  features:
    - toc.integrate
    - navigation.path

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started: 
    - Installation: getting_started/installation/index.md
    - First steps: getting_started/first_steps.md